"""F0 scenarios for spells generated by verified minions and triples."""

import pytest

from hearthstone.engine.entities import HandCard, Spell
from hearthstone.engine.enums import CardIDs, SpellIDs, Tags


def cast(empty_game, player, spell_id, target_index=-1):
    spell = Spell.create_from_db(spell_id)
    player.hand.append(HandCard(uid=empty_game.tavern.get_next_uid(), spell=spell))
    return empty_game.step(
        player.uid, "PLAY", hand_index=len(player.hand) - 1, target_index=target_index
    )


def test_slimy_shield_buffs_and_grants_taunt(empty_game, player, mock_unit) -> None:
    target = mock_unit(CardIDs.RISEN_RIDER, owner_id=player.uid)
    target.tags.discard(Tags.TAUNT)
    player.board = [target]
    before = (target.cur_atk, target.cur_hp)
    assert cast(empty_game, player, SpellIDs.SLIMY_SHIELD, 0)[0]
    assert (target.cur_atk, target.cur_hp) == (before[0] + 1, before[1] + 1)
    assert target.has_taunt


@pytest.mark.parametrize(
    "spell_id,atk,hp",
    [
        (SpellIDs.BLOOD_GEM_BARRAGE, 1, 1),
        (SpellIDs.SHINY_RING, 1, 1),
        (SpellIDs.MISPLACED_TEA_SET, 2, 2),
    ],
)
def test_generated_board_buff_spells(
    empty_game, player, mock_unit, spell_id, atk, hp
) -> None:
    first = mock_unit(CardIDs.RISEN_RIDER, owner_id=player.uid)
    second = mock_unit(CardIDs.CORD_PULLER, owner_id=player.uid)
    player.board = [first, second]
    before = [(unit.cur_atk, unit.cur_hp) for unit in player.board]
    assert cast(empty_game, player, spell_id)[0]
    assert [(unit.cur_atk, unit.cur_hp) for unit in player.board] == [
        (before[0][0] + atk, before[0][1] + hp),
        (before[1][0] + atk, before[1][1] + hp),
    ]


def test_gem_confiscation_buffs_target(empty_game, player, mock_unit) -> None:
    target = mock_unit(CardIDs.RISEN_RIDER, owner_id=player.uid)
    player.board = [target]
    before = (target.cur_atk, target.cur_hp)
    assert cast(empty_game, player, SpellIDs.GEM_CONFISCATION, 0)[0]
    assert (target.cur_atk, target.cur_hp) == (before[0] + 1, before[1] + 1)


def test_triplet_reward_starts_exact_tier_discovery(empty_game, player) -> None:
    reward = Spell.create_from_db(SpellIDs.TRIPLET_REWARD)
    reward.params["tier"] = 2
    player.hand = [HandCard(uid=empty_game.tavern.get_next_uid(), spell=reward)]
    assert empty_game.step(player.uid, "PLAY", hand_index=0)[0]
    assert player.is_discovering
    assert player.discovery.is_exact_tier
    assert player.discovery.discover_tier == 2
