#pragma once
// generated_card_ids.h — AUTO-GENERATED from card_def.py
// DO NOT EDIT MANUALLY — run: python scripts/generate_cpp_effects.py

#include <cstdint>

namespace CardID {
    constexpr int16_t INVALID = -1;

    // --- Tier 1 ---
    constexpr int16_t ANNOY_O_TRON                   = 101;
    constexpr int16_t AUREATE_LAUREATE               = 102;
    constexpr int16_t CORD_PULLER                    = 103;
    constexpr int16_t CRACKLING_CYCLONE              = 104;
    constexpr int16_t DUNE_DWELLER                   = 105;
    constexpr int16_t FLIGHTY_SCOUT                  = 106;
    constexpr int16_t HARMLESS_BONEHEAD              = 107;
    constexpr int16_t MANASABER                      = 108;
    constexpr int16_t MINTED_CORSAIR                 = 109;
    constexpr int16_t MISFIT_DRAGONLING              = 110;
    constexpr int16_t OMINOUS_SEER                   = 111;
    constexpr int16_t PICKY_EATER                    = 112;
    constexpr int16_t RAZORFEN_GEOMANCER             = 113;
    constexpr int16_t RISEN_RIDER                    = 114;
    constexpr int16_t RIVER_SKIPPER                  = 115;
    constexpr int16_t ROT_HIDE_GNOLL                 = 116;
    constexpr int16_t SURF_N_SURF                    = 117;
    constexpr int16_t SWAMPSTRIKER                   = 118;
    constexpr int16_t TUSKED_CAMPER                  = 119;
    constexpr int16_t TWILIGHT_HATCHLING             = 120;
    constexpr int16_t WRATH_WEAVER                   = 121;
    constexpr int16_t MOLTEN_ROCK                    = 122;
    constexpr int16_t FLEEING_FUGITIVE               = 123;
    constexpr int16_t MINI_MYRMIDON                  = 124;

    // --- Tier 2 ---
    constexpr int16_t FREEDEALING_GAMBLER            = 201;
    constexpr int16_t SHELL_COLLECTOR                = 202;
    constexpr int16_t SEWER_RAT                      = 203;
    constexpr int16_t MOON_BACON_JAZZER              = 204;
    constexpr int16_t MECHAGNOME_INTERPRETER         = 205;
    constexpr int16_t BRIARBACK_BOOKIE               = 206;
    constexpr int16_t HUMMING_BIRD                   = 207;
    constexpr int16_t NERUBIAN_DEATHSWARMER          = 208;
    constexpr int16_t OOZELING_GLADIATOR             = 209;
    constexpr int16_t PROPHET_OF_THE_BOAR            = 210;
    constexpr int16_t SALTSCALE_HONCHO               = 211;
    constexpr int16_t SELLEMENTAL                    = 212;
    constexpr int16_t SLEEPY_SUPPORTER               = 213;
    constexpr int16_t TAD                            = 214;
    constexpr int16_t MIND_MUCK                      = 215;
    constexpr int16_t EMBALMING_EXPERT               = 216;
    constexpr int16_t QUILLED_CABBIE                 = 217;
    constexpr int16_t GHOSTLY_YMIRJAR                = 218;
    constexpr int16_t FIRE_BALLER                    = 219;
    constexpr int16_t SNOW_BALLER                    = 220;
    constexpr int16_t IRATE_ROOSTER                  = 221;
    constexpr int16_t SOUL_REWINDER                  = 222;
    constexpr int16_t SURFING_SYLVAR                 = 223;
    constexpr int16_t PATIENT_SCOUT                  = 224;
    constexpr int16_t ANCESTRAL_AUTOMATON            = 225;
    constexpr int16_t METALLIC_HUNTER                = 226;
    constexpr int16_t THOUSANDTH_PAPER_DRAKE         = 227;
    constexpr int16_t LAVA_LURKER                    = 228;
    constexpr int16_t THAUMATURGIST                  = 229;

    // --- Tier 3 ---
    constexpr int16_t BIRD_BUDDY                     = 301;
    constexpr int16_t BUDDING_GREENTHUMB             = 302;
    constexpr int16_t ANNOY_O_MODULE                 = 303;
    constexpr int16_t DEADLY_SPORE                   = 304;
    constexpr int16_t CADAVER_CARETAKER              = 305;
    constexpr int16_t BRINY_BOOTLEGGER               = 306;
    constexpr int16_t HANDLESS_FORSAKEN              = 307;
    constexpr int16_t GREEDY_SNAKETONGUE             = 308;
    constexpr int16_t ROADBOAR                       = 309;
    constexpr int16_t GOLDGRUBBER                    = 310;
    constexpr int16_t GEMSPLITTER                    = 311;
    constexpr int16_t CANOPY_SWINGER                 = 312;
    constexpr int16_t HOT_SPRINGER                   = 313;
    constexpr int16_t RAMPAGER                       = 314;
    constexpr int16_t FELEMENTAL                     = 315;
    constexpr int16_t PRICKLY_PIPER                  = 316;
    constexpr int16_t AMBER_GUARDIAN                 = 317;
    constexpr int16_t HARDY_ORCA                     = 318;
    constexpr int16_t COLDLIGHT_DIVER                = 319;
    constexpr int16_t JELLY_BELLY                    = 320;
    constexpr int16_t ANUBARAK_NERUBIAN_KING         = 321;
    constexpr int16_t ARANASI_ALCHEMIST              = 322;
    constexpr int16_t BASSGILL                       = 323;
    constexpr int16_t BRIARBACK_DRUMMER              = 324;
    constexpr int16_t DEFLECT_O_BOT                  = 325;
    constexpr int16_t PEGGY_STURDYBONE               = 326;
    constexpr int16_t PREHISTORIC_TINKERER           = 327;
    constexpr int16_t ROARING_RECRUITER              = 328;
    constexpr int16_t SCOURFIN                       = 329;
    constexpr int16_t TARDY_TRAVELER                 = 330;
    constexpr int16_t TECHNICAL_ELEMENT              = 331;
    constexpr int16_t THE_GLAD_IATOR                 = 332;
    constexpr int16_t TIMECAPN_HOOKTAIL              = 333;
    constexpr int16_t UNDERHANDED_DEALER             = 334;
    constexpr int16_t WAVELING                       = 335;
    constexpr int16_t WHEELED_CREWMATE               = 336;
    constexpr int16_t WILDFIRE_ELEMENTAL             = 337;
    constexpr int16_t BREAKOUT_MASTERMIND            = 338;
    constexpr int16_t DUSTBONE_DEVASTATOR            = 339;
    constexpr int16_t MAMA_MRRGLTON                  = 340;
    constexpr int16_t METEORITE_CRASHER              = 341;
    constexpr int16_t PAPA_MRRGLTON                  = 342;
    constexpr int16_t PRIVATE_INVESTIGATOR           = 343;
    constexpr int16_t SAND_SWIRLER                   = 344;
    constexpr int16_t DEEP_SEA_ANGLER                = 345;
    constexpr int16_t WAVERIDER                      = 346;

    // --- Tier 4 ---
    constexpr int16_t ACCORD_O_TRON                  = 401;
    constexpr int16_t BLADE_COLLECTOR                = 402;
    constexpr int16_t BONKER                         = 403;
    constexpr int16_t DEVOUT_HELLCALLER              = 404;
    constexpr int16_t EN_DJINN_BLAZER                = 405;
    constexpr int16_t FRIENDLY_GEIST                 = 406;
    constexpr int16_t GEOMAGUS_ROOGUG                = 407;
    constexpr int16_t GREASE_BOT                     = 408;
    constexpr int16_t HEROIC_UNDERDOG                = 409;
    constexpr int16_t HUMONGOZZ                      = 410;
    constexpr int16_t INDUSTRIOUS_DECKHAND           = 411;
    constexpr int16_t KING_BAGURGLE                  = 412;
    constexpr int16_t MARQUEE_TICKER                 = 413;
    constexpr int16_t PRIZED_PROMO_DRAKE             = 414;
    constexpr int16_t PROSTHETIC_HAND                = 415;
    constexpr int16_t RAZORFEN_FLAPPER               = 416;
    constexpr int16_t REFRESHING_ANOMALY             = 417;
    constexpr int16_t SILENT_ENFORCER                = 418;
    constexpr int16_t SINDOREI_STRAIGHT_SHOT         = 419;
    constexpr int16_t SLY_RAPTOR                     = 420;
    constexpr int16_t SOULSPLITTER                   = 421;
    constexpr int16_t SPIRIT_DRAKE                   = 422;
    constexpr int16_t TAVERN_TEMPEST                 = 423;
    constexpr int16_t TUNNEL_BLASTER                 = 424;
    constexpr int16_t WANNABE_GARGOYLE               = 425;
    constexpr int16_t WITCHWING_NESTMATRON           = 426;
    constexpr int16_t TRENCH_FIGHTER                 = 427;
    constexpr int16_t GUNPOWDER_COURIER              = 428;
    constexpr int16_t BREAM_COUNTER                  = 429;
    constexpr int16_t DAGGERSPINE_THRASHER           = 430;
    constexpr int16_t MONSTROUS_MACAW                = 431;
    constexpr int16_t PLANKWALKER                    = 432;
    constexpr int16_t RYLAK_METALHEAD                = 433;
    constexpr int16_t SUNKEN_ADVOCATE                = 434;
    constexpr int16_t TORTOLLAN_BLUE_SHELL           = 435;
    constexpr int16_t TRIGORE_THE_LASHER             = 436;
    constexpr int16_t FLAMING_ENFORCER               = 437;
    constexpr int16_t ICHORON_THE_PROTECTOR          = 438;
    constexpr int16_t PERSISTENT_POET                = 439;
    constexpr int16_t AUTO_ASSEMBLER                 = 440;
    constexpr int16_t CAPTAIN_COOKIE                 = 441;
    constexpr int16_t CLUNKER_JUNKER                 = 442;
    constexpr int16_t DEEPWATER_CHIEFTAIN            = 443;
    constexpr int16_t GLOWING_CINDER                 = 444;
    constexpr int16_t MOTLEY_PHALANX                 = 445;
    constexpr int16_t ABYSSAL_BRUISER                = 446;
    constexpr int16_t CAGEY_CONJURER                 = 447;
    constexpr int16_t RIMESCALE_PRIESTESS            = 448;
    constexpr int16_t SEAFLOOR_RECRUITER             = 449;
    constexpr int16_t ZESTY_SHAKER                   = 450;

    // --- Tier 5 ---
    constexpr int16_t BRANN_BRONZEBEARD              = 501;
    constexpr int16_t TITUS_RIVENDARE                = 502;
    constexpr int16_t DRAKKARI_ENCHANTER             = 503;
    constexpr int16_t GENTLE_DJINNI                  = 504;
    constexpr int16_t INDOMITABLE_MOUNT              = 505;
    constexpr int16_t CHAMPION_OF_THE_PRIMUS         = 506;
    constexpr int16_t CORRUPTED_MYRMIDON             = 507;
    constexpr int16_t SILITHID_BURROWER              = 508;
    constexpr int16_t GHOUL_OF_THE_FEAST             = 509;
    constexpr int16_t TWILIGHT_WATCHER               = 510;
    constexpr int16_t UNFORGIVING_TREANT             = 511;
    constexpr int16_t NOMI_KITCHEN_NIGHTMARE         = 512;
    constexpr int16_t BILE_SPITTER                   = 513;
    constexpr int16_t RAZORFEN_VINEWEAVER            = 514;
    constexpr int16_t CARAPACE_RAISER                = 515;
    constexpr int16_t SHADOWDANCER                   = 516;
    constexpr int16_t FIRESCALE_HOARDER              = 517;
    constexpr int16_t SPIKED_SAVIOR                  = 518;
    constexpr int16_t LEEROY_THE_RECKLESS            = 519;
    constexpr int16_t STUNTDRAKE                     = 520;
    constexpr int16_t WINTERGRASP_GHOUL              = 521;
    constexpr int16_t IRIDESCENT_SKYBLAZER           = 522;
    constexpr int16_t NIUZAO                         = 523;
    constexpr int16_t TWILIGHT_BROODMOTHER           = 524;
    constexpr int16_t COSTUME_ENTHUSIAST             = 525;
    constexpr int16_t ELITE_NAVIGATOR                = 526;
    constexpr int16_t COUSIN_ERRGL                   = 527;
    constexpr int16_t DANCING_BARNSTORMER            = 528;
    constexpr int16_t DUAL_WIELD_CORSAIR             = 529;
    constexpr int16_t KANGORS_APPRENTICE             = 530;
    constexpr int16_t SCRAP_SCRAPER                  = 531;
    constexpr int16_t VIGILANT_BRISTLEMANE           = 532;
    constexpr int16_t VOID_PUP_TRAINER               = 533;
    constexpr int16_t DARKCREST_STRATEGIST           = 534;
    constexpr int16_t GLOWSCALE                      = 535;
    constexpr int16_t SHOWY_CYCLIST                  = 536;
    constexpr int16_t TRANQUIL_MEDITATIVE            = 537;

    // --- Tier 6 ---
    constexpr int16_t GOLDRINN_THE_GREAT_WOLF        = 601;
    constexpr int16_t CHARLGA                        = 602;
    constexpr int16_t SLITHERSPEAR_LORD_OF_GAINS     = 603;
    constexpr int16_t LORD_OF_THE_RUINS              = 604;
    constexpr int16_t FAMISHED_FELBAT                = 605;
    constexpr int16_t SHIP_MASTER_EUDORA             = 606;
    constexpr int16_t AVALANCHE_CALLER               = 607;
    constexpr int16_t ULTRAVIOLET_ASCENDANT          = 608;
    constexpr int16_t IGNITION_SPECIALIST            = 609;
    constexpr int16_t FAUNA_WHISPERER                = 610;
    constexpr int16_t YOUNG_MURK_EYE                 = 611;
    constexpr int16_t FIRE_FORGED_EVOKER             = 612;
    constexpr int16_t SANGUINE_REFINER               = 613;
    constexpr int16_t BLOODSNOUT_WARLORD             = 614;
    constexpr int16_t DEATHLY_STRIKER                = 615;
    constexpr int16_t WHIRLING_LASS_O_MATIC          = 616;
    constexpr int16_t ARCHAEDAS                      = 617;
    constexpr int16_t NIGHTMARE_PAR_TEA_GUEST        = 618;
    constexpr int16_t SUNDERED_MATRIARCH             = 619;
    constexpr int16_t PRIMITIVE_PAINTER              = 620;
    constexpr int16_t MOAT_CUSTODIAN                 = 621;
    constexpr int16_t UNLEASHED_MANA_SURGE           = 622;
    constexpr int16_t WARPWING                       = 623;
    constexpr int16_t GROUNDBREAKER                  = 624;
    constexpr int16_t TORRENTIAL_RUINER              = 625;

    // --- Tier 7 ---
    constexpr int16_t SEA_WITCH_ZARJIRA              = 709;
    constexpr int16_t CAPTAIN_SANDERS                = 701;
    constexpr int16_t HIGHKEEPER_RA                  = 702;
    constexpr int16_t THE_LAST_ONE_STANDING          = 703;
    constexpr int16_t SANGUINE_CHAMPION              = 704;
    constexpr int16_t PSYCHUS                        = 705;
    constexpr int16_t OBSIDIAN_RAVAGER               = 706;
    constexpr int16_t STITCHED_SALVAGER              = 707;
    constexpr int16_t FUTUREFIN                      = 708;

    // --- Tokens ---
    constexpr int16_t MICROBOT                       = 901;
    constexpr int16_t SKELETON                       = 902;
    constexpr int16_t CUBLING                        = 903;
    constexpr int16_t TWILIGHT_WHELP                 = 904;
    constexpr int16_t CRAB                           = 905;
    constexpr int16_t TURTLE                         = 906;
    constexpr int16_t WATER_DROPLET                  = 907;
    constexpr int16_t HAND                           = 908;
    constexpr int16_t GOLEM                          = 909;
}

namespace EffectID {
    constexpr int16_t NONE = 0;
    constexpr int16_t CRAB_DEATHRATTLE               = 5001;  // E_DR_CRAB32
}
