from __future__ import annotations

from typing import Any, Dict

from .card_def import build_card_db
from .enums import CardIDs, EffectIDs, MechanicType, SpellIDs, Tags, UnitType

TIER_COPIES = {1: 16, 2: 15, 3: 13, 4: 11, 5: 9, 6: 7, 7: 3}

# Cards rotated out of the live pool (patch 36.6.1). Kept in CARD_DB for
# back-compat, but never dealt into shops or offered by discoveries.
# NOTE: DUNE_DWELLER returns to the live pool in the 2026-09-22 patch —
# remember to remove it from this set after the patch.
ROTATED_OUT = {
    CardIDs.MONSTROUS_MACAW,  # Parrot rotated out in 36.6.1
    # --- T1 ---
    CardIDs.ANNOY_O_TRON,
    CardIDs.DUNE_DWELLER,
    CardIDs.MANASABER,
    CardIDs.MINTED_CORSAIR,
    CardIDs.MISFIT_DRAGONLING,
    CardIDs.PICKY_EATER,
    CardIDs.SURF_N_SURF,
    CardIDs.SWAMPSTRIKER,
    CardIDs.TWILIGHT_HATCHLING,
    # --- T2 ---
    CardIDs.FREEDEALING_GAMBLER,
    CardIDs.SEWER_RAT,
    CardIDs.MOON_BACON_JAZZER,
    CardIDs.BRIARBACK_BOOKIE,
    CardIDs.PROPHET_OF_THE_BOAR,
    CardIDs.SALTSCALE_HONCHO,
    CardIDs.SLEEPY_SUPPORTER,
    CardIDs.EMBALMING_EXPERT,
    CardIDs.QUILLED_CABBIE,
    CardIDs.GHOSTLY_YMIRJAR,
    CardIDs.IRATE_ROOSTER,
    # --- T3 ---
    CardIDs.BIRD_BUDDY,
    CardIDs.BUDDING_GREENTHUMB,
    CardIDs.BRINY_BOOTLEGGER,
    CardIDs.GREEDY_SNAKETONGUE,
    CardIDs.GOLDGRUBBER,
    CardIDs.GEMSPLITTER,
    CardIDs.CANOPY_SWINGER,
    CardIDs.HOT_SPRINGER,
    CardIDs.RAMPAGER,
    CardIDs.FELEMENTAL,
    CardIDs.PRICKLY_PIPER,
    CardIDs.HARDY_ORCA,
    CardIDs.COLDLIGHT_DIVER,
    CardIDs.JELLY_BELLY,
    CardIDs.ANUBARAK_NERUBIAN_KING,
    CardIDs.ARANASI_ALCHEMIST,
    CardIDs.BASSGILL,
    CardIDs.PEGGY_STURDYBONE,
    CardIDs.PREHISTORIC_TINKERER,
    CardIDs.SCOURFIN,
    CardIDs.TARDY_TRAVELER,
    CardIDs.TECHNICAL_ELEMENT,
    CardIDs.THE_GLAD_IATOR,
    CardIDs.UNDERHANDED_DEALER,
    CardIDs.WHEELED_CREWMATE,
    # --- T4 ---
    CardIDs.GREASE_BOT,
    CardIDs.INDUSTRIOUS_DECKHAND,
    CardIDs.KING_BAGURGLE,
    CardIDs.MARQUEE_TICKER,
    CardIDs.PRIZED_PROMO_DRAKE,
    CardIDs.SILENT_ENFORCER,
    CardIDs.SOULSPLITTER,
    CardIDs.SPIRIT_DRAKE,
    CardIDs.TUNNEL_BLASTER,
    CardIDs.WANNABE_GARGOYLE,
    CardIDs.WITCHWING_NESTMATRON,
    CardIDs.DAGGERSPINE_THRASHER,
    CardIDs.PLANKWALKER,
    CardIDs.RYLAK_METALHEAD,
    CardIDs.SUNKEN_ADVOCATE,
    CardIDs.TRIGORE_THE_LASHER,
    CardIDs.ICHORON_THE_PROTECTOR,
    # --- T5 ---
    CardIDs.GENTLE_DJINNI,
    CardIDs.INDOMITABLE_MOUNT,
    CardIDs.CHAMPION_OF_THE_PRIMUS,
    CardIDs.CORRUPTED_MYRMIDON,
    CardIDs.SILITHID_BURROWER,
    CardIDs.GHOUL_OF_THE_FEAST,
    CardIDs.TWILIGHT_WATCHER,
    CardIDs.UNFORGIVING_TREANT,
    CardIDs.CARAPACE_RAISER,
    CardIDs.SHADOWDANCER,
    CardIDs.SPIKED_SAVIOR,
    CardIDs.STUNTDRAKE,
    CardIDs.WINTERGRASP_GHOUL,
    CardIDs.IRIDESCENT_SKYBLAZER,
    CardIDs.NIUZAO,
    CardIDs.TWILIGHT_BROODMOTHER,
    CardIDs.ELITE_NAVIGATOR,
    # --- T6 ---
    CardIDs.CHARLGA,
    CardIDs.SLITHERSPEAR_LORD_OF_GAINS,
    CardIDs.LORD_OF_THE_RUINS,
    CardIDs.FAMISHED_FELBAT,
    CardIDs.SHIP_MASTER_EUDORA,
    CardIDs.AVALANCHE_CALLER,
    CardIDs.ULTRAVIOLET_ASCENDANT,
    CardIDs.YOUNG_MURK_EYE,
    CardIDs.BLOODSNOUT_WARLORD,
    CardIDs.WHIRLING_LASS_O_MATIC,
    CardIDs.ARCHAEDAS,
    CardIDs.SUNDERED_MATRIARCH,
}

TAVERN_SLOTS = {1: 3, 2: 4, 3: 4, 4: 5, 5: 5, 6: 6}
TIER_UPGRADE_COSTS = {2: 5, 3: 7, 4: 8, 5: 9, 6: 10}

MECHANIC_DEFAULTS = {
    MechanicType.BLOOD_GEM: (1, 1),
    MechanicType.ELEMENTAL_BUFF: (0, 0),
    MechanicType.ELEMENTAL_BUFF_BONUS: (0, 0),
    MechanicType.TAVERN_SPELL_POWER: (0, 0),
}

COST_BUY = 3
COST_REROLL = 1
SPELLS_PER_ROLL = 1

# =====================================================================
# Card Database — generated from card_def.py (single source of truth)
# =====================================================================
CARD_DB: Dict[str, Any] = build_card_db()

# =====================================================================
# Spell Database
# =====================================================================
SPELL_DB: Dict[str, Any] = {
    SpellIDs.TAVERN_COIN: {
        "name": "Tavern Coin",
        "tier": 1,
        "cost": 1,
        "effect": "GAIN_GOLD",
        "params": {"gold": 1},
    },
    SpellIDs.BANANA: {
        "name": "Banana",
        "tier": 1,
        "cost": 3,
        "effect": "BUFF_MINION",
        "params": {"atk": 2, "hp": 2},
    },
    SpellIDs.BLOOD_GEM: {
        "name": "Blood Gem",
        "tier": 0,
        "cost": 0,
        "effect": "BUFF_MINION",
        "params": {"atk": 1, "hp": 1},
        "pool": False,
    },
    SpellIDs.POINTY_ARROW: {
        "name": "Pointy Arrow",
        "tier": 1,
        "cost": 1,
        "effect": "BUFF_MINION",
        "params": {"atk": 4, "hp": 0},
    },
    SpellIDs.FORTIFY: {
        "name": "Fortify",
        "tier": 1,
        "cost": 1,
        "effect": "BUFF_MINION",
        "params": {"atk": 0, "hp": 3, "tags": {Tags.TAUNT}},
    },
    SpellIDs.APPLE: {
        "name": "Apple",
        "tier": 1,
        "cost": 1,
        "effect": "BUFF_TAVERN",
        "params": {"atk": 1, "hp": 2},
    },
    SpellIDs.SURF_SPELLCRAFT: {
        "name": "Surf Spellcraft",
        "tier": 1,
        "cost": 0,
        "effect": "ATTACH_CRAB_DR",
        "params": {"effect_id": EffectIDs.CRAB_DEATHRATTLE, "count": 1},
        "is_temporary": True,
        "pool": False,
    },
    SpellIDs.SLIMY_SHIELD: {
        "name": "Slimy Shield",
        "tier": 2,
        "cost": 0,
        "effect": "BUFF_MINION",
        "params": {"atk": 1, "hp": 1, "tags": {Tags.TAUNT}},
        "pool": False,
    },
    SpellIDs.BLOOD_GEM_BARRAGE: {
        "name": "Blood Gem Barrage",
        "tier": 3,
        "cost": 0,
        "effect": "BUFF_ALL_FRIENDLY",
        "params": {"atk": 1, "hp": 1},
        "pool": False,
    },
    SpellIDs.GEM_CONFISCATION: {
        "name": "Gem Confiscation",
        "tier": 4,
        "cost": 0,
        "effect": "BUFF_MINION",
        "params": {"atk": 1, "hp": 1},
        "pool": False,
    },
    SpellIDs.TRIPLET_REWARD: {
        "name": "Triple Reward",
        "tier": 1,
        "cost": 0,
        "effect": "DISCOVER_TIER_UP",
        "is_temporary": False,
        "pool": False,
    },
    SpellIDs.HAUNTED_CARAPACE: {
        "name": "Haunted Carapace",
        "tier": 5,
        "cost": 0,
        "effect": "BUFF_ALL_FRIENDLY",
        "params": {"atk": 3, "hp": 1},
        "pool": False,
    },
    SpellIDs.STAFF_OF_ENRICHMENT: {
        "name": "Staff of Enrichment",
        "tier": 5,
        "cost": 0,
        "effect": "BUFF_TAVERN",
        "params": {"atk": 2, "hp": 2},
        "pool": False,
    },
    SpellIDs.SHINY_RING: {
        "name": "Shiny Ring",
        "tier": 5,
        "cost": 0,
        "effect": "BUFF_ALL_FRIENDLY",
        "params": {"atk": 1, "hp": 1},
        "pool": False,
    },
    SpellIDs.MOUNTING_AVALANCHE: {
        "name": "Mounting Avalanche",
        "tier": 6,
        "cost": 0,
        "effect": "BUFF_MINION",
        "params": {"atk": 2, "hp": 2},
        "pool": False,
    },
    SpellIDs.MISPLACED_TEA_SET: {
        "name": "Misplaced Tea Set",
        "tier": 6,
        "cost": 0,
        "effect": "BUFF_ALL_BY_TYPE",
        "params": {"atk": 2, "hp": 2},
        "pool": False,
    },
    SpellIDs.TOMB_TURNING: {
        "name": "Tomb Turning",
        "tier": 5,
        "cost": 0,
        "effect": "BUFF_MINION",
        "params": {"atk": 2, "hp": 2},
        "pool": False,
    },
    # --- B2 expansion spells (2026-09) ---
    SpellIDs.CHEFS_CHOICE: {
        "name": "Chef's Choice",
        "tier": 2,
        "cost": 2,
        "effect": "TRANSFORM_TO_RANDOM_SAME_TYPE",
        "params": {},
        "pool": False,
    },
    SpellIDs.DEEPWATER_CLAN: {
        "name": "Deepwater Clan",
        "tier": 2,
        "cost": 2,
        "effect": "BUFF_MINION_AND_BOARD_TYPE",
        "params": {"atk": 2, "hp": 2, "unit_type": UnitType.MURLOC},
        "pool": False,
    },
    SpellIDs.MINI_MYRMIDON_SPELLCRAFT: {
        "name": "Mini-Myrmidon Spellcraft",
        "tier": 1,
        "cost": 0,
        "effect": "BUFF_MINION_TURN",
        "params": {"atk": 2, "hp": 0},
        "is_temporary": True,
        "pool": False,
    },
    SpellIDs.THAUMATURGIST_SPELLCRAFT: {
        "name": "Thaumaturgist Spellcraft",
        "tier": 2,
        "cost": 0,
        "effect": "BUFF_MINION_TURN_SCALING",
        "params": {
            "base_atk": 1,
            "base_hp": 1,
            "scaling_key": "spells_cast",
            "per_n": 3,
            "step_atk": 1,
            "step_hp": 1,
        },
        "is_temporary": True,
        "pool": False,
    },
    SpellIDs.DEEP_SEA_ANGLER_SPELLCRAFT: {
        "name": "Deep-Sea Angler Spellcraft",
        "tier": 3,
        "cost": 0,
        "effect": "BUFF_MINION_TURN_TAGS",
        "params": {"atk": 2, "hp": 6, "tags": {Tags.TAUNT}},
        "is_temporary": True,
        "pool": False,
    },
    SpellIDs.WAVERIDER_SPELLCRAFT: {
        "name": "Waverider Spellcraft",
        "tier": 3,
        "cost": 0,
        "effect": "BUFF_MINION_COND_TAGS",
        "params": {"atk": 2, "hp": 2, "cond_type": UnitType.NAGA, "tags": {Tags.WINDFURY}},
        "is_temporary": True,
        "pool": False,
    },
    SpellIDs.RIMESCALE_PRIESTESS_SPELLCRAFT: {
        "name": "Rimescale Priestess Spellcraft",
        "tier": 4,
        "cost": 0,
        "effect": "GET_RANDOM_STAT_SPELL",
        "params": {},
        "is_temporary": True,
        "pool": False,
    },
    SpellIDs.DARKCREST_STRATEGIST_SPELLCRAFT: {
        "name": "Darkcrest Strategist Spellcraft",
        "tier": 5,
        "cost": 0,
        "effect": "GET_RANDOM_UNIT_TIER_BY_TURN",
        "params": {"unit_type": UnitType.NAGA, "base_tier": 1, "per_turn": 1, "max_tier": 6},
        "is_temporary": True,
        "pool": False,
    },
    SpellIDs.GLOWSCALE_SPELLCRAFT: {
        "name": "Glowscale Spellcraft",
        "tier": 5,
        "cost": 0,
        "effect": "BUFF_MINION_TAGS",
        "params": {"tags": {Tags.DIVINE_SHIELD}},
        "is_temporary": True,
        "pool": False,
    },
    SpellIDs.TRANQUIL_MEDITATIVE_SPELLCRAFT: {
        "name": "Tranquil Meditative Spellcraft",
        "tier": 5,
        "cost": 0,
        "effect": "TAVERN_SPELL_BONUS_GLOBAL",
        "params": {"atk": 1, "hp": 1},
        "is_temporary": True,
        "pool": False,
    },
    SpellIDs.SEA_WITCH_SPELLCRAFT: {
        "name": "Sea Witch Spellcraft",
        "tier": 7,
        "cost": 0,
        "effect": "COPY_RANDOM_OTHER_TAVERN_MINION",
        "params": {},
        "is_temporary": True,
        "pool": False,
    },
}
